services:
  - type: web
    name: chatapp-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node src/index.js
    healthCheckPath: /api/v1/health
    envVars:
      - key: NODE_ENV
        value: production